// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventmanagement.proxies;

public class ProgramItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject programItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EventManagement.ProgramItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		NumberOfVisitorsGoing("NumberOfVisitorsGoing"),
		ProgramItem_Artist("EventManagement.ProgramItem_Artist"),
		ProgramItem_Day("EventManagement.ProgramItem_Day"),
		ProgramItem_Stage("EventManagement.ProgramItem_Stage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProgramItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ProgramItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject programItemMendixObject)
	{
		if (programItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, programItemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.programItemMendixObject = programItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static eventmanagement.proxies.ProgramItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new eventmanagement.proxies.ProgramItem(context, mendixObject);
	}

	public static eventmanagement.proxies.ProgramItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return eventmanagement.proxies.ProgramItem.initialize(context, mendixObject);
	}

	public static java.util.List<eventmanagement.proxies.ProgramItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> eventmanagement.proxies.ProgramItem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * @return value of NumberOfVisitorsGoing
	 */
	public final java.lang.Integer getNumberOfVisitorsGoing()
	{
		return getNumberOfVisitorsGoing(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfVisitorsGoing
	 */
	public final java.lang.Integer getNumberOfVisitorsGoing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfVisitorsGoing.toString());
	}

	/**
	 * Set value of NumberOfVisitorsGoing
	 * @param numberofvisitorsgoing
	 */
	public final void setNumberOfVisitorsGoing(java.lang.Integer numberofvisitorsgoing)
	{
		setNumberOfVisitorsGoing(getContext(), numberofvisitorsgoing);
	}

	/**
	 * Set value of NumberOfVisitorsGoing
	 * @param context
	 * @param numberofvisitorsgoing
	 */
	public final void setNumberOfVisitorsGoing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofvisitorsgoing)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfVisitorsGoing.toString(), numberofvisitorsgoing);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProgramItem_Artist
	 */
	public final eventmanagement.proxies.Artist getProgramItem_Artist() throws com.mendix.core.CoreException
	{
		return getProgramItem_Artist(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgramItem_Artist
	 * @throws com.mendix.core.CoreException
	 */
	public final eventmanagement.proxies.Artist getProgramItem_Artist(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventmanagement.proxies.Artist result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProgramItem_Artist.toString());
		if (identifier != null) {
			result = eventmanagement.proxies.Artist.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProgramItem_Artist
	 * @param programitem_artist
	 */
	public final void setProgramItem_Artist(eventmanagement.proxies.Artist programitem_artist)
	{
		setProgramItem_Artist(getContext(), programitem_artist);
	}

	/**
	 * Set value of ProgramItem_Artist
	 * @param context
	 * @param programitem_artist
	 */
	public final void setProgramItem_Artist(com.mendix.systemwideinterfaces.core.IContext context, eventmanagement.proxies.Artist programitem_artist)
	{
		if (programitem_artist == null) {
			getMendixObject().setValue(context, MemberNames.ProgramItem_Artist.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProgramItem_Artist.toString(), programitem_artist.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProgramItem_Day
	 */
	public final eventmanagement.proxies.Day getProgramItem_Day() throws com.mendix.core.CoreException
	{
		return getProgramItem_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgramItem_Day
	 * @throws com.mendix.core.CoreException
	 */
	public final eventmanagement.proxies.Day getProgramItem_Day(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventmanagement.proxies.Day result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProgramItem_Day.toString());
		if (identifier != null) {
			result = eventmanagement.proxies.Day.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProgramItem_Day
	 * @param programitem_day
	 */
	public final void setProgramItem_Day(eventmanagement.proxies.Day programitem_day)
	{
		setProgramItem_Day(getContext(), programitem_day);
	}

	/**
	 * Set value of ProgramItem_Day
	 * @param context
	 * @param programitem_day
	 */
	public final void setProgramItem_Day(com.mendix.systemwideinterfaces.core.IContext context, eventmanagement.proxies.Day programitem_day)
	{
		if (programitem_day == null) {
			getMendixObject().setValue(context, MemberNames.ProgramItem_Day.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProgramItem_Day.toString(), programitem_day.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProgramItem_Stage
	 */
	public final eventmanagement.proxies.Stage getProgramItem_Stage() throws com.mendix.core.CoreException
	{
		return getProgramItem_Stage(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgramItem_Stage
	 * @throws com.mendix.core.CoreException
	 */
	public final eventmanagement.proxies.Stage getProgramItem_Stage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventmanagement.proxies.Stage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProgramItem_Stage.toString());
		if (identifier != null) {
			result = eventmanagement.proxies.Stage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProgramItem_Stage
	 * @param programitem_stage
	 */
	public final void setProgramItem_Stage(eventmanagement.proxies.Stage programitem_stage)
	{
		setProgramItem_Stage(getContext(), programitem_stage);
	}

	/**
	 * Set value of ProgramItem_Stage
	 * @param context
	 * @param programitem_stage
	 */
	public final void setProgramItem_Stage(com.mendix.systemwideinterfaces.core.IContext context, eventmanagement.proxies.Stage programitem_stage)
	{
		if (programitem_stage == null) {
			getMendixObject().setValue(context, MemberNames.ProgramItem_Stage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProgramItem_Stage.toString(), programitem_stage.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return programItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final eventmanagement.proxies.ProgramItem that = (eventmanagement.proxies.ProgramItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
