// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventmanagement.proxies;

public class Visitor extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EventManagement.Visitor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateOfBirth("DateOfBirth"),
		ReceiveNewsletter("ReceiveNewsletter"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		Visitor_Ticket("EventManagement.Visitor_Ticket"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Visitor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Visitor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject visitorMendixObject)
	{
		super(context, visitorMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, visitorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static eventmanagement.proxies.Visitor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new eventmanagement.proxies.Visitor(context, mendixObject);
	}

	public static eventmanagement.proxies.Visitor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return eventmanagement.proxies.Visitor.initialize(context, mendixObject);
	}

	public static java.util.List<eventmanagement.proxies.Visitor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> eventmanagement.proxies.Visitor.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of ReceiveNewsletter
	 */
	public final java.lang.Boolean getReceiveNewsletter()
	{
		return getReceiveNewsletter(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceiveNewsletter
	 */
	public final java.lang.Boolean getReceiveNewsletter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ReceiveNewsletter.toString());
	}

	/**
	 * Set value of ReceiveNewsletter
	 * @param receivenewsletter
	 */
	public final void setReceiveNewsletter(java.lang.Boolean receivenewsletter)
	{
		setReceiveNewsletter(getContext(), receivenewsletter);
	}

	/**
	 * Set value of ReceiveNewsletter
	 * @param context
	 * @param receivenewsletter
	 */
	public final void setReceiveNewsletter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean receivenewsletter)
	{
		getMendixObject().setValue(context, MemberNames.ReceiveNewsletter.toString(), receivenewsletter);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Visitor_Ticket
	 */
	public final java.util.List<eventmanagement.proxies.Ticket> getVisitor_Ticket() throws com.mendix.core.CoreException
	{
		return getVisitor_Ticket(getContext());
	}

	/**
	 * @param context
	 * @return value of Visitor_Ticket
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<eventmanagement.proxies.Ticket> getVisitor_Ticket(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<eventmanagement.proxies.Ticket> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Visitor_Ticket.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(eventmanagement.proxies.Ticket.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Visitor_Ticket
	 * @param visitor_ticket
	 */
	public final void setVisitor_Ticket(java.util.List<eventmanagement.proxies.Ticket> visitor_ticket)
	{
		setVisitor_Ticket(getContext(), visitor_ticket);
	}

	/**
	 * Set value of Visitor_Ticket
	 * @param context
	 * @param visitor_ticket
	 */
	public final void setVisitor_Ticket(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<eventmanagement.proxies.Ticket> visitor_ticket)
	{
		var identifiers = visitor_ticket
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Visitor_Ticket.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final eventmanagement.proxies.Visitor that = (eventmanagement.proxies.Visitor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
